services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=finantialhub'
      - 'POSTGRES_PASSWORD=Secret4321'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'    # AMQP protocol
      - '15672:15672'  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest