spring.application.name=finantialhubapi

spring.datasource.url=jdbc:postgresql://localhost:5432/finantialhub
spring.datasource.username=admin
spring.datasource.password=Secret4321

spring.sql.init.mode=always
spring.datasource.driver-class-name=org.postgresql.Driver

# Price API (Ruby)
price.api.base-url=http://localhost:4567